### ISSUE TITLE
Many tools have extraneous toolforge. in URL

### ISSUE THREAD

**Issue by Samwalton9** [gopavasanth/ToolWatch#3]
A tool that I was playing around with, `articleimpact.toolforge.org` is present in ToolWatch, but it has the URL as [toolforge.articleimpact.toolforge.org](https://toolforge.articleimpact.toolforge.org/), which does not resolve, so it is flagged as unavailable. I think the extra `toolforge.` should not be present - the correct URL is [articleimpact.toolforge.org](https://articleimpact.toolforge.org/)

**Comment by sohomdatta1** [comment]
This should be fixed :)
